<a href="https://colab.research.google.com/github/hemanthrkz/all-projects/blob/main/preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# ===============================
# NLP Preprocessing in Python
# ===============================

import re
from sklearn.feature_extraction.text import (
    CountVectorizer,
    TfidfVectorizer,
    ENGLISH_STOP_WORDS
)

# ==========================================
# 1. Text Preprocessing
# ==========================================

text = "Natural Language Processing is AMAZING, in 2026!"

# Convert to lowercase and remove numbers/special characters
clean = re.sub(r"[^a-z\s]", "", text.lower())

# Tokenization
tokens = clean.split()

# Remove stop words
tokens = [t for t in tokens if t not in ENGLISH_STOP_WORDS]

print("Original Text:")
print(text)

print("\nClean Text:")
print(clean)

print("\nTokens after removing stop words:")
print(tokens)

# ==========================================
# 2. Bag of Words (BoW)
# ==========================================

sentences = [
    "i love nlp",
    "nlp is fun",
    "i love ai"
]

cv = CountVectorizer()
bow = cv.fit_transform(sentences)

print("\nVocabulary:")
print(cv.get_feature_names_out())

print("\nBag of Words Matrix:")
print(bow.toarray())

# ==========================================
# 3. TF-IDF
# ==========================================

docs = [
    "the cat sat",
    "the dog ran",
    "the bird flew"
]

tv = TfidfVectorizer()
matrix = tv.fit_transform(docs)

words = dict(zip(tv.get_feature_names_out(), matrix.toarray()[0].round(2)))

print("\nTF-IDF Values (First Document):")
print(words)

print("\nWeight of 'the':", words["the"])
print("Weight of 'cat':", words["cat"])

Original Text:
Natural Language Processing is AMAZING, in 2026!

Clean Text:
natural language processing is amazing in 

Tokens after removing stop words:
['natural', 'language', 'processing', 'amazing']

Vocabulary:
['ai' 'fun' 'is' 'love' 'nlp']

Bag of Words Matrix:
[[0 0 0 1 1]
 [0 1 1 0 1]
 [1 0 0 1 0]]

TF-IDF Values (First Document):
{'bird': np.float64(0.0), 'cat': np.float64(0.65), 'dog': np.float64(0.0), 'flew': np.float64(0.0), 'ran': np.float64(0.0), 'sat': np.float64(0.65), 'the': np.float64(0.39)}

Weight of 'the': 0.39
Weight of 'cat': 0.65
